apiVersion: v1
kind: Pod
metadata:
  name: wa11y
  namespace: default
  labels:
    name: wa11y
spec:
  containers:
    - name: irc
      image: docker.io/library/wa11y:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
