apiVersion: apps/v1
kind: Deployment
metadata:
  name: irc-server
spec:
  selector:
    matchLabels:
      app: irc-server
  template:
    metadata:
      labels:
        app: irc-server
    spec:
      containers:
        - name: irc-server
          image: docker.io/library/irc-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 6697
---
apiVersion: v1
kind: Service
metadata:
  name: irc-server
spec:
  selector:
    app: irc-server
  ports:
    - port: 6697
      targetPort: 6697
