apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-server
  namespace: global
spec:
  selector:
    matchLabels:
      app: state-server
  template:
    metadata:
      labels:
        app: state-server
    spec:
      containers:
        - name: state-server
          image: docker.io/library/state-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: state-server
spec:
  selector:
    app: state-server
  ports:
    - port: 5003
      targetPort: 5003
